name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bunx --bun eslint .

      - name: Run Astro check
        run: bun run check

      - name: Run type check
        run: bun run type-check
